[package]
name = "my_project"
version = "0.1.0"
authors = ["Achraf Benjana <achrafdrs03@outlook.com>"]

[dependencies]
# Add your dependencies here

[[bin]]
name = "my_executable"
path = "src/main.rs"

[[lib]]
name = "my_library"
path = "src/lib.rs"
